version: '3'

services:
  web:
    image: nginx:1.19-alpine
    volumes:
      - $PWD/app:/var/www/html
      - $PWD/docker/web/default.conf:/etc/nginx/conf.d/default.conf
    tty: true
    ports:
      - 8080:80
    depends_on:
        - app

  app:
    image: php:7.4-fpm-alpine
    volumes:
      - $PWD/app:/var/www/html
      - $PWD/docker/app/php.ini:/usr/local/etc/php/php.ini
      - $PWD/docker/app/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf
    working_dir: /var/www/html
    environment:
        COMPOSER_ALLOW_SUPERUSER: 1
        COMPOSER_HOME: /composer
        PATH: $PATH:/composer/vendor/bin
    command: >
        /bin/sh -c "apk add --no-cache icu-dev autoconf make g++ gcc mysql-client &&
            docker-php-ext-install pdo_mysql &&
            curl -s http://getcomposer.org/installer | php -- --install-dir=/usr/bin/ --filename=composer &&
            composer install &&
            php-fpm"
    tty: true
    depends_on:
        - db

  db:
    image: mysql:8
    ports:
        - 3306:3306
    volumes:
        - $PWD/docker/db:/docker-entrypoint-initdb.d:rw
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=l7
      - MYSQL_USER=l7
      - MYSQL_PASSWORD=passwd

